### ISSUE TITLE
Could not find package

### ISSUE THREAD

**Issue by CyanBook** [R6API/client#18]
```
[InvalidArgumentException]
Could not find package r6api/client at any version matching your PHP version 7.0.32.0
```

Help me!

**Comment by Korbeil** [comment]
Hi @ThePaxxerello, thanks for posting !
Actually this package only supports PHP from version 7.1 to upper versions (actually never tried it on PHP 7.3 but will add it to CI when I have some time.
I'll suggest you upgrading your PHP version, you can also see here: http://php.net/supported-versions.php that PHP 7.0.* is actually not on active support which means it's not recommended to use it.
