### ISSUE TITLE
StatisticApi - DTO & Serializer

### ISSUE THREAD

**Issue by Korbeil** [R6API/client#5]
Create a data model to store StatisticApi response and create a Serializer to make it easy to convert response to this model.
For this endpoint, we have a lot of sub-models such as Operators !!

Please discuss about the models you wanna use in thread before preparing it for PR.

**Comment by stygiansabyss** [comment]
I use https://github.com/jenssegers/model when I want things like this, but I do use laravel on my sites.  So not sure how you'd feel about that.

**Comment by stygiansabyss** [comment]
For the DTO, it would be nice to have helper methods to group the constants as well.  Something like pve()/pvp() etc.
